= 客户端的响应数据

客户端的响应数据是指那些由客户端导致的可由客户端修复的响应数据。
//通常如果请求还未到达服务端就发生了异常，会产生客户端的响应数据。

== 客户端异常
这是一个通用的响应状态，当发生预期外的异常时使用该响应状态。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "client_error",
  "message": "客户端请求异常",
  "data": "{具体异常}", //<1>
}
----
<1> 提供具体异常的描述信息（如果有），便于定位问题

== 网络异常
这是一个通用的网络级别响应状态，当发生预期外的网络级别的异常时使用该响应状态。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "network_error",
  "message": "网络异常",
  "data": "{具体异常}", //<1>
}
----
<1> 提供具体异常的描述信息（如果有），便于定位问题

== 无网络连接
客户端在一个无网络的环境下发送请求时，会产生该响应状态。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "network_broken",
  "message": "没有网络连接",
}
----

此响应状态通常是由用户网络环境不稳定导致的，
在网络正常时进入系统，在随后的访问中失去网络连接，
只能说让用户在一个良好的网络环境下进行操作，无法从根本上解决。

== 请求地址不存在
客户端请求一个不存在的地址时，会产生该响应状态。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "url_not_exist",
  "message": "请求地址'{请求地址}'不存在",
  "data": {
     url: "{请求地址}"
  }
}
----

此响应状态通常是由服务端变更了域名而客户端没有同步更新导致的；
出现此响应状态后，需要指定正确的请求地址。

== 请求超时
客户端在请求时指定了超时时间，
服务端在超时时间范围内未返回响应信息，
会产生该响应状态。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "timeout",
  "message": "请求时长已超过最大限制'{超时秒数}'秒",
  "data":{超时秒数}
}
----

此响应状态通常是由客户端指定了过短的超时时间导致的；
出现此响应状态后，客户端可通过调大超时时间选项解决；
服务端也需要注意优化程序提高响应速度。

== 跨域请求
客户端在使用``XMLHttpRequest``发送请求时出现了跨域异常，会产生该响应状态。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "cors_error",
  "message": "不允许从'{原域}'跨域访问'{目标域}'",
  "data":{
      "source":"{原域}",
      "target":"{目标域}",
  }
}
----

此响应状态通常是由【系统的域名环境和跨域请求】配置不当导致的；
出现此响应状态后，需要调整域名环境或者配置跨域选项。