= 概述
:website: https://peacetrue.github.io
:app-group: com.github.peacetrue.result
:app-name: peacetrue-result
:foresight-repo-id: 876fc1b0-c84e-4df6-b970-5112bf6de4ad
:imagesdir: docs/antora/modules/ROOT/assets/images

image:https://img.shields.io/github/actions/workflow/status/peacetrue/{app-name}/main.yml?branch=master["GitHub Workflow Status",link="https://github.com/peacetrue/{app-name}/actions"]
image:https://snyk.io/test/github/peacetrue/{app-name}/badge.svg["Snyk",link="https://app.snyk.io/org/peacetrue"]
image:https://api-public.service.runforesight.com/api/v1/badge/success?repoId={foresight-repo-id}["Foresight",link="https://foresight.thundra.io/repositories/github/peacetrue/{app-name}/test-runs"]
image:https://img.shields.io/codecov/c/github/peacetrue/{app-name}/master["Codecov",link="https://app.codecov.io/gh/peacetrue/{app-name}"]
image:https://img.shields.io/nexus/r/{app-group}/{app-name}?label={app-name}&server=https%3A%2F%2Foss.sonatype.org%2F["{app-name}",link="https://search.maven.org/search?q={app-name}"]

//@formatter:off

== 简介（What）

{website}/{app-name}/[{app-name}] 是一个响应结果组件，用于统一处理接口返回的数据。

.特性
* 优化响应结果编码体系
* 人性化响应结果描述
* 国际化响应结果描述
* 自动装配成功响应结果
* 自动装配异常响应结果

== 背景（Why）

服务端接口返回数据时，往往需要提供一些属性，指示服务端对此次请求的处理状态（响应状态）。
如果处理成功，客户端可以正常执行接下来的业务；
如果处理失败，则需要根据失败原因针对性处理。

//NOTE: HTTP 状态码也可以指示响应状态，但通常不能满足实际业务中的需求。

假设，服务端需要返回如下格式的用户数据：

[source%nowrap,json]
----
{
    "id": 1,
    "name": "张三"
}
----

封装响应状态之后，返回的数据如下：

.响应结果
[source%nowrap,json]
----
{
    "code": "success",//<1>
    "message": "操作成功",//<2>
    "data": { //<3>
      "id": 1,
      "name": "张三"
    }
}
----
<1> 编码：指示响应状态的唯一标志
<2> 描述：用于操作失败时分析具体原因
<3> 数据：存放实际需要返回的数据

响应结果组件提供了标准的数据结构，
封装了成功时的数据和失败时的异常，
优化了失败时的提示信息，使调用者可以快速定位原因。

== 用法（How）

.运行环境
* JDK 1.8 及以上
* Spring Boot 1 系列最高版本 1.5.22.RELEASE，对应组件 1 系列版本
* Spring Boot 2 系列最低版本 &nbsp;&nbsp;2.0.0.RELEASE，对应组件 2 系列版本

.核心类库，提供响应结果的数据结构和常用类型。
[source%nowrap,maven]
----
<dependency>
  <groupId>com.github.peacetrue.result</groupId>
  <artifactId>peacetrue-result-core</artifactId>
  <version>2.1.0</version>
</dependency>
----

.构建类库，构造响应结果描述信息，支持国际化
[source%nowrap,maven]
----
<dependency>
  <groupId>com.github.peacetrue.result</groupId>
  <artifactId>peacetrue-result-builder</artifactId>
  <version>2.1.0</version>
</dependency>
----

.成功类库，封装成功时返回的数据
[source%nowrap,maven]
----
<dependency>
  <groupId>com.github.peacetrue.result</groupId>
  <artifactId>peacetrue-result-success</artifactId>
  <version>2.1.0</version>
</dependency>
----

.异常类库，封装异常时返回的数据，提供抽象的异常转换体系
[source%nowrap,maven]
----
<dependency>
  <groupId>com.github.peacetrue.result</groupId>
  <artifactId>peacetrue-result-exception</artifactId>
  <version>2.1.0</version>
</dependency>
----

.异常支持类库，实现具体异常的转换
[source%nowrap,maven]
----
<dependency>
  <groupId>com.github.peacetrue.result</groupId>
  <artifactId>peacetrue-result-exception-support</artifactId>
  <version>2.1.0</version>
</dependency>
----

== 参与者（Who）

. peace(xiayouxue@hotmail.com)

== 活动（When）

初始提交于 2021-08-14，最近提交于 2022-10-30。

== 许可证（License）

https://github.com/peacetrue/{app-name}/blob/master/LICENSE[Apache License 2.0^]
