= 参数范围错误
接口要求传入指定范围内的参数，但实际传入了范围外的参数，会产生该响应状态。

这是一个通用的响应状态，当出现不在预期内的参数范围错误时使用此状态。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "parameter_range_error",
  "message": "参数'{参数名}'的值'{参数值}'范围错误",
  "data": {  
      "name":"{参数名}", //<1>
      "value":"{参数值}", //<2>
      "type":"{参数类型}", //<3>
      "range":{参数范围值}, //<4>
  }
}
----
<1> 出现错误的参数名
<2> 参数名对应的参数值
<3> 服务端要求的参数范围类型
<4> 服务端要求的参数范围值

== 必须是指定值
接口要求某项参数必须是指定选项中的一个，但实际在选项之外，会产生该响应状态；
例如：接口要求性别传入【男】或【女】，但实际传入了【1】。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "not_in",
  "message": "参数'{参数名}'的值'{参数值}'不是'{选项}'中的一个",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
      "options":{选项},
  }
}
----

== 必须小于指定值
接口要求某项参数必须小于某个值，但实际等于或大于该值，会产生该响应状态；
例如：接口要求传入年龄小于200岁，但实际传入了"999"。

参数的类型可以是数值、日期、字符长度等可比较的类型。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "not_lt",
  "message": "参数'{参数名}'的值'{参数值}'不能大于或等于'{指定值}'",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
      "max":{指定值},
  }
}
----

== 必须小于或等于指定值
类似于 <<_必须小于指定值>>。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "not_le",
  "message": "参数'{参数名}'的值'{参数值}'不能大于'{指定值}'",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
      "max":{指定值},
  }
}
----

== 必须大于指定值
类似于 <<_必须小于指定值>>。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "not_gt",
  "message": "参数'{参数名}'的值'{参数值}'不能小于或等于'{指定值}'",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
      "min":{指定值},
  }
}
----

== 必须大于或等于指定值
类似于 <<_必须小于指定值>>。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "not_ge",
  "message": "参数'{参数名}'的值'{参数值}'不能小于'{指定值}'",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
      "min":{指定值},
  }
}
----


////
== 必须是邮箱格式
接口要求某项参数必须是邮箱格式，但实际不是邮箱格式，会产生该响应状态。
例如：接口要求传入邮箱地址，但实际传入了电话号码"18718272909"。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "not_email",
  "message": "参数'{参数名}'的值'{参数值}'不是有效的邮箱",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
  }
}
----
////


//== 必须是链接格式

//== 必须是电话格式

== 记录不存在
接口要求某项参数指定一条必须存在的记录，但实际指定了不存在的记录，会产生该响应状态。
例如：查询用户时接口要求传入一个已存在的用户主键，但实际传入的用户主键"-1"不存在。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "record_absent",
  "message": "'{参数名}'为'{参数值}'的记录不存在",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
  }
}
----

== 记录已存在
接口要求某项参数指定一条必须不存在的记录，但实际指定了已存在的记录，会产生该响应状态。
例如：新增用户时接口要求传入一个不存在的用户手机号，但实际传入的用户手机号"18718272909"已存在。

响应数据的标准结构为：
[source%nowrap,json]
----
{
  "code": "record_exist",
  "message": "'{参数名}'为'{参数值}'的记录已存在",
  "data": {
      "name":"{参数名}",
      "value":"{参数值}",
  }
}
----